# Generated by Django 4.0.4 on 2022-04-20 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        ('criteria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteria',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='project.project'),
        ),
    ]
