# Generated by Django 4.0.4 on 2022-04-20 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('criteria', '0003_remove_criteria_project_criteria_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criteria',
            name='project',
        ),
    ]
