# Generated by Django 4.0.4 on 2022-04-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criteria', '0004_remove_criteria_project'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='criteria',
            field=models.ManyToManyField(to='criteria.criteria'),
        ),
    ]
