# Generated by Django 4.0.4 on 2022-04-20 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_criteria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('weight', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='criteria',
            field=models.ManyToManyField(to='project.criteria'),
        ),
    ]
