# Generated by Django 4.0.4 on 2022-04-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criteria', '0004_remove_criteria_project'),
        ('project', '0005_alter_project_criteria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='criteria',
            field=models.ManyToManyField(related_name='+', to='criteria.criteria'),
        ),
    ]
