# Generated by Django 4.0.4 on 2022-04-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criteria', '0004_remove_criteria_project'),
        ('project', '0006_alter_project_criteria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='criteria',
            field=models.ManyToManyField(blank=True, null=True, to='criteria.criteria'),
        ),
    ]
